name: Deploy to QA

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_qa:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      MPKIT_URL: 'https://docskit-da.staging.oregon.platform-os.com/'
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      ASSET_PREFIX: 'https://cdn.staging.oregon.platform-os.com/instances/11963/assets/'
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          submodules: true

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install Dependencies
        run: |
          cd src
          npm install --legacy-peer-deps

      - name: pos-cli
        shell: sh
        run: |
          npm install -g @platformos/pos-cli

      - name: Build
        shell: sh
        run: |
          set -eu
          echo $MPKIT_URL
          npm ci
          npm run build

      - name: Deploy
        timeout-minutes: 10
        shell: sh
        run: |
          set -eu
          pos-cli deploy
